import { WorkflowPhase, AIInsight, TransformationProject } from "../types";

// Multiple company datasets for selection functionality
export const COMPANY_DATASETS = {
  mastec: {
    project: {
      id: "1",
      clientName: "MasTec Power Delivery",
      industry: "Infrastructure & Construction",
      engagementType: "Finance Transformation Blueprint",
      status: "analysis" as const,
      progress: 42,
      aiAcceleration: 47,
      startDate: "2024-01-15",
      estimatedCompletion: "2024-03-28",
      teamMembers: ["Sarah Johnson", "Mike Chen", "Lisa Rodriguez", "AI Assistant", "David Kim"],
      hackettIPMatches: 1247,
      region: "North America",
      projectValue: 12400000,
      currentPhase: 3,
    },
    aiInsights: [] as AIInsight[], // Will be populated below
  },
  "global-tech": {
    project: {
      id: "2",
      clientName: "Global Tech Solutions",
      industry: "Technology & Software",
      engagementType: "Finance Operations Excellence",
      status: "roadmap" as const,
      progress: 67,
      aiAcceleration: 52,
      startDate: "2024-02-01",
      estimatedCompletion: "2024-04-15",
      teamMembers: ["Jennifer Liu", "Carlos Rodriguez", "Emily Zhang", "AI Assistant", "Robert Chen"],
      hackettIPMatches: 1589,
      region: "Global",
      projectValue: 18700000,
      currentPhase: 5,
    },
    aiInsights: [] as AIInsight[], // Will be populated below
  },
  "meridian-manufacturing": {
    project: {
      id: "3",
      clientName: "Meridian Manufacturing Corp",
      industry: "Manufacturing & Industrial",
      engagementType: "Digital Finance Transformation",
      status: "implementation" as const,
      progress: 85,
      aiAcceleration: 41,
      startDate: "2023-11-20",
      estimatedCompletion: "2024-02-29",
      teamMembers: ["Alex Thompson", "Maria Santos", "James Wilson", "AI Assistant", "Sophie Kim"],
      hackettIPMatches: 923,
      region: "Europe",
      projectValue: 8900000,
      currentPhase: 6,
    },
    aiInsights: [] as AIInsight[], // Will be populated below
  },
  "apex-financial": {
    project: {
      id: "4",
      clientName: "Apex Financial Services",
      industry: "Financial Services",
      engagementType: "Regulatory Compliance & Finance",
      status: "data-collection" as const,
      progress: 28,
      aiAcceleration: 59,
      startDate: "2024-02-15",
      estimatedCompletion: "2024-05-10",
      teamMembers: ["Rachel Green", "Kevin Park", "Lisa Anderson", "AI Assistant", "Mark Thompson"],
      hackettIPMatches: 1834,
      region: "North America",
      projectValue: 15600000,
      currentPhase: 2,
    },
    aiInsights: [] as AIInsight[], // Will be populated below
  },
};

// AI Insights for each company
const MASTEC_AI_INSIGHTS: AIInsight[] = [
  {
    id: "insight_1",
    type: "automation",
    title: "Automated Invoice Processing",
    description: "Implement AI-powered invoice processing to reduce manual effort by 75% and improve accuracy",
    confidence: 92,
    impact: "high",
    source: "Process Analysis",
    phase: 3,
    actionable: true,
    estimatedValue: 850000,
    timeframe: "3 months",
  },
  {
    id: "insight_2",
    type: "benchmark",
    title: "Working Capital Optimization",
    description: "Current DSO of 45 days vs industry best practice of 28 days presents improvement opportunity",
    confidence: 88,
    impact: "high",
    source: "Hackett Benchmarks",
    phase: 3,
    actionable: true,
    estimatedValue: 1200000,
    timeframe: "6 months",
  },
];

const GLOBALTECH_AI_INSIGHTS: AIInsight[] = [
  {
    id: "insight_3",
    type: "recommendation",
    title: "Cloud-Based FP&A Platform",
    description: "Migrate to cloud-based financial planning platform for real-time analytics and reporting",
    confidence: 94,
    impact: "high",
    source: "Technology Assessment",
    phase: 5,
    actionable: true,
    estimatedValue: 2100000,
    timeframe: "4 months",
  },
  {
    id: "insight_4",
    type: "opportunity",
    title: "Shared Services Expansion",
    description: "Expand shared services model globally to achieve economies of scale",
    confidence: 86,
    impact: "medium",
    source: "Organizational Analysis",
    phase: 4,
    actionable: true,
    estimatedValue: 3400000,
    timeframe: "12 months",
  },
];

const MERIDIAN_AI_INSIGHTS: AIInsight[] = [
  {
    id: "insight_5",
    type: "risk",
    title: "ERP System Integration Risk",
    description: "Legacy system integration poses implementation risks that need mitigation strategies",
    confidence: 78,
    impact: "medium",
    source: "Risk Assessment",
    phase: 6,
    actionable: true,
    timeframe: "Ongoing",
  },
  {
    id: "insight_6",
    type: "automation",
    title: "Predictive Maintenance Analytics",
    description: "Implement predictive analytics for equipment maintenance cost optimization",
    confidence: 91,
    impact: "high",
    source: "Data Analytics",
    phase: 6,
    actionable: true,
    estimatedValue: 1800000,
    timeframe: "8 months",
  },
];

const APEX_AI_INSIGHTS: AIInsight[] = [
  {
    id: "insight_7",
    type: "benchmark",
    title: "Regulatory Reporting Automation",
    description: "Automate regulatory reporting processes to ensure compliance and reduce manual errors",
    confidence: 96,
    impact: "high",
    source: "Compliance Analysis",
    phase: 2,
    actionable: true,
    estimatedValue: 950000,
    timeframe: "5 months",
  },
  {
    id: "insight_8",
    type: "opportunity",
    title: "Risk Management Enhancement",
    description: "Implement advanced risk analytics platform for better decision making",
    confidence: 89,
    impact: "high",
    source: "Risk Framework",
    phase: 2,
    actionable: true,
    estimatedValue: 1600000,
    timeframe: "7 months",
  },
];

// Populate AI insights for each company
COMPANY_DATASETS.mastec.aiInsights = MASTEC_AI_INSIGHTS;
COMPANY_DATASETS["global-tech"].aiInsights = GLOBALTECH_AI_INSIGHTS;
COMPANY_DATASETS["meridian-manufacturing"].aiInsights = MERIDIAN_AI_INSIGHTS;
COMPANY_DATASETS["apex-financial"].aiInsights = APEX_AI_INSIGHTS;

// Default to MasTec for backward compatibility
export const SAMPLE_PROJECT: TransformationProject = COMPANY_DATASETS.mastec.project;

export const WORKFLOW_PHASES: WorkflowPhase[] = [
  {
    id: 1,
    title: "Project Initiation & Client Onboarding",
    description: "AI-enhanced client intelligence gathering with automated data ingestion and Hackett IP matching",
    status: "completed",
    aiAcceleration: 57,
    duration: "3 days",
    traditionalDuration: "7 days",
    hackettIP: ["Client Profiling Templates", "Industry Benchmarks", "Engagement Playbooks", "SOW Analysis Framework"],
    deliverables: ["Client Profile", "SOW Analysis", "Data Collection Plan", "Team Assignment"],
    aiSuggestions: [
      "Auto-populated client profile from public data and industry databases",
      "Recommended data collection approach based on client complexity",
      "Risk assessment using historical engagement patterns",
      "Optimal team composition recommendation",
    ],
    keyActivities: ["Client intelligence gathering", "SOW review", "Stakeholder mapping", "Tool setup"],
    dependencies: [],
    teamRole: ["Project Director", "Engagement Manager", "AI Assistant"],
    clientTasks: ["Provide SOW", "Identify key stakeholders", "Grant data access"],
    progress: 100,
    estimatedCompletion: "2024-01-18",
    successMetrics: ["Client profile accuracy >95%", "Data access granted", "Team alignment achieved"],
  },
  {
    id: 2,
    title: "Parallel Workstream Management",
    description: "AI-orchestrated data collection with intelligent survey generation and automated interview scheduling",
    status: "completed",
    aiAcceleration: 60,
    duration: "2 weeks",
    traditionalDuration: "5 weeks",
    hackettIP: ["Survey Templates", "Interview Guides", "CMM Frameworks", "Benchmark Data Portal"],
    deliverables: ["Benchmark Data", "Interview Insights", "Survey Results", "CMM Assessment", "Technology Inventory"],
    aiSuggestions: [
      "Dynamic survey questions based on interview themes",
      "Automated interview scheduling optimization",
      "Real-time data validation and gap identification",
      "Intelligent stakeholder prioritization",
    ],
    keyActivities: ["Executive interviews (10-15 sessions)", "Stakeholder surveys (~50 responses)", "CMM workshops (3 weeks)", "Benchmark data collection"],
    dependencies: ["Phase 1 completion"],
    teamRole: ["Senior Manager", "Analysts", "HR Partner", "Technology Lead"],
    clientTasks: ["Interview participation", "Survey completion", "Data provision"],
    progress: 100,
    estimatedCompletion: "2024-02-01",
    riskFactors: ["Survey response rate", "Executive availability", "Data quality"],
    successMetrics: ["15 executive interviews completed", "50+ survey responses", "CMM baseline established"],
  },
  {
    id: 3,
    title: "AI-Powered Synthesis & Analysis",
    description: "Intelligent data triangulation with automated gap analysis and benchmark comparison",
    status: "in-progress",
    aiAcceleration: 65,
    duration: "1 week",
    traditionalDuration: "3 weeks",
    hackettIP: ["Analysis Frameworks", "Gap Analysis Tools", "Benchmark Datasets", "Best Practice Library"],
    deliverables: ["Current State Assessment", "Gap Analysis", "Benchmark Comparison", "Target Model Definition"],
    aiSuggestions: [
      "Automated pattern recognition across data sources",
      "Intelligent gap prioritization based on impact",
      "Dynamic benchmark selection for peer comparison",
      "AI-generated insights with confidence scoring",
    ],
    keyActivities: ["Data triangulation", "Gap identification", "Benchmark analysis", "Target state definition"],
    dependencies: ["Phase 2 data completion"],
    teamRole: ["Analytics Lead", "AI Specialist", "Domain Expert"],
    clientTasks: ["Review preliminary findings", "Validate insights"],
    progress: 75,
    estimatedCompletion: "2024-02-08",
    riskFactors: ["Data quality issues", "Conflicting stakeholder input"],
    successMetrics: ["All data sources integrated", "Key gaps identified", "Target model approved"],
  },
  {
    id: 4,
    title: "Initiative Identification & Prioritization",
    description: "AI-generated recommendations with intelligent value quantification and ROI analysis",
    status: "pending",
    aiAcceleration: 70,
    duration: "1.5 weeks",
    traditionalDuration: "4 weeks",
    hackettIP: ["Initiative Templates", "ROI Calculators", "Prioritization Frameworks", "Value Models"],
    deliverables: ["Initiative Portfolio", "Business Cases", "ROI Analysis", "Risk Assessment"],
    aiSuggestions: [
      "Automated initiative generation from gap analysis",
      "Intelligent value quantification using benchmarks",
      "Risk-adjusted ROI calculations",
      "Portfolio optimization recommendations",
    ],
    keyActivities: ["Initiative development", "Value quantification", "Risk assessment", "Prioritization"],
    dependencies: ["Phase 3 completion"],
    teamRole: ["Strategy Lead", "Financial Analyst", "Risk Manager"],
    clientTasks: ["Initiative review", "Priority confirmation"],
    progress: 0,
    estimatedCompletion: "2024-02-19",
    riskFactors: ["Value estimation accuracy", "Resource constraints"],
    successMetrics: ["15-20 initiatives identified", "Business cases developed", "Priorities agreed"],
  },
  {
    id: 5,
    title: "Roadmap Development",
    description: "Dynamic roadmap construction with automated dependency mapping and resource optimization",
    status: "pending",
    aiAcceleration: 55,
    duration: "1 week",
    traditionalDuration: "2.5 weeks",
    hackettIP: ["Roadmap Templates", "Dependency Models", "Resource Planning Tools", "Timeline Frameworks"],
    deliverables: ["Transformation Roadmap", "Resource Plan", "Timeline", "Dependency Matrix"],
    aiSuggestions: [
      "Automated dependency detection and mapping",
      "Optimal sequencing based on value and feasibility",
      "Resource optimization across initiatives",
      "Dynamic timeline adjustment for constraints",
    ],
    keyActivities: ["Roadmap design", "Dependency mapping", "Resource planning", "Timeline development"],
    dependencies: ["Phase 4 completion"],
    teamRole: ["Program Manager", "Resource Planner", "Timeline Analyst"],
    clientTasks: ["Resource availability confirmation", "Timeline approval"],
    progress: 0,
    estimatedCompletion: "2024-02-26",
    riskFactors: ["Resource availability", "Timeline constraints"],
    successMetrics: ["Roadmap completed", "Dependencies mapped", "Timeline approved"],
  },
  {
    id: 6,
    title: "Client Review & Handover",
    description: "Interactive presentation with collaborative decision-making and professional deliverable generation",
    status: "pending",
    aiAcceleration: 45,
    duration: "1 week",
    traditionalDuration: "2 weeks",
    hackettIP: ["Presentation Templates", "Decision Frameworks", "Handover Guides", "Documentation Standards"],
    deliverables: ["Executive Presentation", "Detailed Documentation", "Implementation Guide", "Success Metrics"],
    aiSuggestions: [
      "Auto-generated executive summary with key insights",
      "Interactive presentation elements for engagement",
      "Personalized recommendations by stakeholder",
      "Automated documentation formatting and export",
    ],
    keyActivities: ["Presentation preparation", "Stakeholder review", "Decision facilitation", "Documentation"],
    dependencies: ["Phase 5 completion"],
    teamRole: ["Presentation Lead", "Client Partner", "Documentation Specialist"],
    clientTasks: ["Review materials", "Make decisions", "Plan implementation"],
    progress: 0,
    estimatedCompletion: "2024-03-05",
    riskFactors: ["Stakeholder alignment", "Decision delays"],
    successMetrics: ["Presentation delivered", "Decisions made", "Handover completed"],
  },
  {
    id: 7,
    title: "Implementation Tracking",
    description: "Continuous monitoring with AI-powered progress analysis and benefit realization tracking",
    status: "pending",
    aiAcceleration: 40,
    duration: "Ongoing",
    traditionalDuration: "Ongoing",
    hackettIP: ["Tracking Dashboards", "KPI Frameworks", "Progress Models", "Benefit Tracking Tools"],
    deliverables: ["Progress Dashboard", "Benefit Reports", "Risk Updates", "Success Metrics"],
    aiSuggestions: ["Automated progress tracking from multiple sources", "Predictive analysis for timeline and budget", "Risk early warning system", "Benefit realization optimization"],
    keyActivities: ["Progress monitoring", "Benefit tracking", "Risk management", "Optimization"],
    dependencies: ["Phase 6 completion"],
    teamRole: ["Implementation Manager", "Analytics Lead", "PMO"],
    clientTasks: ["Provide updates", "Address issues", "Validate benefits"],
    progress: 0,
    estimatedCompletion: "Ongoing",
    riskFactors: ["Implementation delays", "Resource changes", "Scope creep"],
    successMetrics: ["Benefits realized", "Timeline adherence", "Quality maintained"],
  },
];

export const AI_INSIGHTS: AIInsight[] = [
  {
    id: "1",
    type: "automation",
    title: "AI-Powered Invoice Processing Priority",
    description:
      "Based on MasTec's current AP volume (15K invoices/month) and Hackett benchmark data, implementing AI-powered invoice processing could reduce cycle time by 78% and save $2.3M annually.",
    confidence: 94,
    impact: "high",
    source: "Hackett Benchmark Database + Client Data Analysis",
    phase: 4,
    actionable: true,
    estimatedValue: 2300000,
    timeframe: "6-8 months",
    dependencies: ["ERP integration", "OCR technology", "Approval workflows"],
  },
  {
    id: "2",
    type: "opportunity",
    title: "Quick Win: Expense Management Mobile Solution",
    description: "Client data shows 23% higher expense processing costs vs. Digital World Class. Mobile expense capture implementation could deliver $1.2M annual savings with 6-week implementation.",
    confidence: 87,
    impact: "medium",
    source: "Client Survey Data + CMM Workshop Results",
    phase: 4,
    actionable: true,
    estimatedValue: 1200000,
    timeframe: "6 weeks",
    dependencies: ["Mobile app development", "Policy updates", "User training"],
  },
  {
    id: "3",
    type: "risk",
    title: "Oracle Fusion Integration Complexity",
    description: "Legacy system integration with Oracle Fusion may require additional effort. Similar infrastructure clients experienced 15% timeline extension. Recommend phased approach.",
    confidence: 82,
    impact: "medium",
    source: "Historical Project Database + Industry Analysis",
    phase: 5,
    actionable: true,
    timeframe: "Ongoing risk",
    dependencies: ["Technical assessment", "Integration planning", "Vendor coordination"],
  },
  {
    id: "4",
    type: "benchmark",
    title: "Month-End Close Performance Gap",
    description: "Current 8-day close vs. 3-day Digital World Class benchmark. AI-powered reconciliation could achieve 4-day close, saving $850K annually in FTE costs.",
    confidence: 91,
    impact: "high",
    source: "Hackett Finance Benchmark 2024",
    phase: 3,
    actionable: true,
    estimatedValue: 850000,
    timeframe: "4-6 months",
    dependencies: ["Process automation", "Data quality", "Training"],
  },
  {
    id: "5",
    type: "recommendation",
    title: "Shared Services Center Optimization",
    description: "Based on Hackett GBS model, centralizing AP, AR, and GL functions could reduce costs by 35% while improving service quality. ROI: 280% over 3 years.",
    confidence: 89,
    impact: "high",
    source: "Hackett GBS Operating Model + Client Interviews",
    phase: 4,
    actionable: true,
    estimatedValue: 4200000,
    timeframe: "12-18 months",
    dependencies: ["Organizational change", "Technology platform", "Process standardization"],
  },
];

export const PHASE_COLORS = {
  1: "bg-blue-100 text-blue-800 border-blue-200",
  2: "bg-green-100 text-green-800 border-green-200",
  3: "bg-purple-100 text-purple-800 border-purple-200",
  4: "bg-orange-100 text-orange-800 border-orange-200",
  5: "bg-pink-100 text-pink-800 border-pink-200",
  6: "bg-indigo-100 text-indigo-800 border-indigo-200",
  7: "bg-gray-100 text-gray-800 border-gray-200",
};
